name: Backend Continuous Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f backend/Dockerfile .

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_BACKEND }}
      IMAGE_TAG: ${{ env.IMAGE_TAG }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Setup kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG}" > $HOME/.kube/config

      - name: Set kustomize image tag
        run: |
          cd backend/k8s
          kustomize edit set image backend=${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Deploy to Kubernetes
        run: |
          cd backend/k8s
          kustomize build | kubectl apply -f -
