name: Frontend Continuous Deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  REACT_APP_MOVIE_API_URL: http://localhost:5000

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run linter
        working-directory: starter/frontend
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: starter/frontend
        run: npm ci

      - name: Run Tests
        working-directory: starter/frontend
        run: CI=true npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build Docker image
        run: |
          docker build --build-arg REACT_APP_MOVIE_API_URL=${REACT_APP_MOVIE_API_URL} -t $ECR_REPOSITORY:$IMAGE_TAG ./starter/frontend

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_FRONTEND }}
      IMAGE_TAG: ${{ github.sha }}
      KUBECONFIG: ${{ secrets.KUBECONFIG }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl and kustomize
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          curl -sLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64
          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          echo "${KUBECONFIG}" | base64 --decode > $HOME/.kube/config

      - name: Set kustomize image tag
        run: |
          cd starter/frontend/k8s
          kustomize edit set image frontend=${ECR_REPOSITORY}:${IMAGE_TAG}

      - name: Deploy to EKS
        run: |
          cd starter/frontend/k8s
          kustomize build | kubectl apply -f -